[package]
name = "gg_namecard_gen"
version = "0.1.0"
edition = "2024"

[dependencies]
ab_glyph = "0.2.31"
anyhow = "1.0.99"
image = "0.25.6"
imageproc = "0.25.0"
puddle-farm-api-client_openapi_client = "1.0.0"
serde = "1.0.219"
serde_json = "1.0.143"
